KNOWN_ISSUES = [
    {
        "category": "Setup integrazione",
        "title": "ConfigEntryNotReady / platform not ready / will retry",
        "patterns": ["configentrynotready", "platform not ready", "will retry"],
        "diagnosis": "Il dispositivo o servizio non e' raggiungibile durante il caricamento. Home Assistant di solito ritenta automaticamente.",
        "safe_response": "Attesa e ricontrollo; se persiste, verificare rete, alimentazione o disponibilita' del servizio.",
        "automation_level": "safe",
    },
    {
        "category": "Setup integrazione",
        "title": "ConfigEntryAuthFailed / authentication failed",
        "patterns": ["configentryauthfailed", "authentication failed", "reauthentication"],
        "diagnosis": "Le credenziali o il token dell'integrazione non sono piu' validi.",
        "safe_response": "Solo notifica: serve ri-autenticazione da Impostazioni > Dispositivi e Servizi.",
        "automation_level": "manual",
    },
    {
        "category": "Setup integrazione",
        "title": "ConfigEntryError / error setting up entry",
        "patterns": ["configentryerror", "error setting up entry", "error setting up config entry"],
        "diagnosis": "Errore permanente di setup: configurazione corrotta, incompatibilita' o bug di integrazione.",
        "safe_response": "Reload config entry se viene rilevato un entry_id; altrimenti solo notifica.",
        "automation_level": "guarded",
    },
    {
        "category": "Setup integrazione",
        "title": "Requirements for X not found",
        "patterns": ["requirements for", "not found", "failed to install requirement"],
        "diagnosis": "Una libreria Python richiesta dall'integrazione non si e' installata correttamente.",
        "safe_response": "Solo notifica, oppure restart Home Assistant se esplicitamente autorizzato.",
        "automation_level": "guarded",
    },
    {
        "category": "YAML e configurazione",
        "title": "Indentazione errata / tab YAML",
        "patterns": ["found character that cannot start any token", "found character that can't start any token", "scannererror", "while scanning for the next token"],
        "diagnosis": "Il YAML contiene tab o indentazione non valida.",
        "safe_response": "Solo notifica con indicazione di eseguire Configuration Check prima del riavvio.",
        "automation_level": "manual",
    },
    {
        "category": "YAML e configurazione",
        "title": "Entity name con caratteri speciali",
        "patterns": ["invalid entity id", "invalid slug", "entity_id is an invalid entity id"],
        "diagnosis": "Un entity_id o nome configurato non rispetta il formato atteso da Home Assistant.",
        "safe_response": "Solo notifica: serve correzione nome/entity_id o rename controllato.",
        "automation_level": "manual",
    },
    {
        "category": "Automazioni",
        "title": "Automazione che non scatta o si ferma",
        "patterns": ["condition did not pass", "stopped because", "automation trace", "unknown service"],
        "diagnosis": "Il trace dell'automazione e' il punto migliore per capire trigger, condizioni e step falliti.",
        "safe_response": "Solo notifica con richiesta di controllare Settings > Automations > Traces.",
        "automation_level": "manual",
    },
    {
        "category": "Automazioni",
        "title": "Trigger da ritorno unavailable",
        "patterns": ["from unavailable", "unavailable to", "state changed from unavailable"],
        "diagnosis": "Un trigger di stato puo' partire quando l'entita' torna da unavailable a uno stato normale.",
        "safe_response": "Solo notifica: suggerisce not_from: unavailable o condizione di esclusione.",
        "automation_level": "manual",
    },
    {
        "category": "Automazioni",
        "title": "Azione bloccata da entita' non disponibile",
        "patterns": ["referenced entities", "not available", "entity not available", "not found"],
        "diagnosis": "Una sequenza puo' fermarsi se una entita' controllata non esiste o non e' disponibile.",
        "safe_response": "Solo notifica: suggerisce guard condition o continue_on_error.",
        "automation_level": "manual",
    },
    {
        "category": "Emulated Hue",
        "title": "Client esterno chiama entita' non piu' esistente",
        "patterns": ["emulated_hue", "entity not found"],
        "diagnosis": "Un client compatibile Hue sta chiedendo a Home Assistant una vecchia entita' che non esiste piu'.",
        "safe_response": "Solo notifica: rimuovere il dispositivo dal client vocale/app Hue compatibile e rifare discovery.",
        "automation_level": "manual",
    },
    {
        "category": "Automazioni",
        "title": "Loop di riavvio causato da automazione",
        "patterns": ["hassio.reboot", "homeassistant.restart", "restart loop", "reboot loop"],
        "diagnosis": "Una automazione che riavvia senza resettare il trigger puo' creare un loop di reboot.",
        "safe_response": "Solo notifica; lo stop automatico richiede rilevamento loop e allow_automation_disable=true.",
        "automation_level": "guarded",
    },
    {
        "category": "Automazioni",
        "title": "Setup automazione fallito o timeout salvataggio",
        "patterns": ["new automation setup failed", "waiting for it to setup has timed out", "automation setup failed"],
        "diagnosis": "Il reload automazioni puo' fallire per errori YAML o configurazione non valida.",
        "safe_response": "Solo notifica con suggerimento Configuration Check.",
        "automation_level": "manual",
    },
    {
        "category": "Automazioni",
        "title": "Automazione disabilitata per trigger inesistente",
        "patterns": ["failed to setup triggers and has been disabled", "unknown entity registry entry", "unknown entity"],
        "diagnosis": "Un trigger punta a una entita' cancellata o a un registry id non piu' valido.",
        "safe_response": "L'app puo' confermare lo stop dell'automazione se consentito; la correzione strutturale richiede sostituire il trigger.",
        "automation_level": "guarded",
    },
    {
        "category": "Automazioni",
        "title": "Script gia' in esecuzione",
        "patterns": ["already running", "homeassistant.components.script"],
        "diagnosis": "Uno script in mode single e' stato richiamato mentre era ancora running.",
        "safe_response": "L'app puo' chiamare script.turn_off se allow_script_stop=true; poi conviene valutare mode restart o queued.",
        "automation_level": "safe",
    },
    {
        "category": "Automazioni",
        "title": "Servizio non supportato dall'entita'",
        "patterns": ["does not support action", "servicenotsupported"],
        "diagnosis": "Una automazione o chiamata manuale usa un servizio non supportato da quella entita'.",
        "safe_response": "Solo notifica: correggere servizio, dominio o controllo supported_features.",
        "automation_level": "manual",
    },
    {
        "category": "Template",
        "title": "Template loop detected",
        "patterns": ["template loop detected", "skipping template render"],
        "diagnosis": "Un template sensor osserva un insieme troppo ampio di stati e viene innescato anche dai propri aggiornamenti.",
        "safe_response": "Solo notifica: convertire il sensore in trigger-based template o restringere le entita' osservate.",
        "automation_level": "manual",
    },
    {
        "category": "Luci e dispositivi",
        "title": "Toggle loop / stato luce non sincronizzato",
        "patterns": ["light.toggle", "toggle", "state not updated", "oscillation"],
        "diagnosis": "L'uso di toggle con stato non sincronizzato puo' invertire il comando nei cicli successivi.",
        "safe_response": "Rilevamento live delle oscillazioni; suggerisce turn_on/turn_off espliciti o update_entity.",
        "automation_level": "guarded",
    },
    {
        "category": "Luci e dispositivi",
        "title": "light.turn_on fallisce con Unknown error",
        "patterns": ["light.turn_on", "unknown error", "template light"],
        "diagnosis": "Una luce template o integrazione luce puo' non accettare piu' il comando dopo aggiornamenti.",
        "safe_response": "Solo notifica: verificare template e log dell'integrazione.",
        "automation_level": "manual",
    },
    {
        "category": "Aggiornamenti",
        "title": "Update gia' installato o versione specifica non supportata",
        "patterns": ["no update available", "no update available for app", "installing a specific version is not supported", "update.ha_mcp_self_healer_update"],
        "diagnosis": "E' stata richiesta un'installazione update quando l'entita' non ha aggiornamenti disponibili o non supporta versioni specifiche.",
        "safe_response": "Solo notifica: evitare chiamate update.install inutili e aggiornare lo store/rebuildare l'add-on.",
        "automation_level": "manual",
    },
    {
        "category": "Aggiornamenti",
        "title": "Unique ID duplicato su update entity",
        "patterns": ["does not generate unique ids", "already exists", "home_assistant_core_version_latest"],
        "diagnosis": "Home Assistant ha creato o visto due entita' update con lo stesso unique_id.",
        "safe_response": "Solo notifica: spesso si risolve con reload/restart; se persiste va pulita l'entita' duplicata.",
        "automation_level": "guarded",
    },
    {
        "category": "Core Home Assistant",
        "title": "InvalidStateError durante rimozione entita'",
        "patterns": ["invalidstateerror", "async_remove", "async_reset"],
        "diagnosis": "Errore interno durante reset/rimozione di una entity platform; spesso transitorio o bug di integrazione/core.",
        "safe_response": "Solo notifica: se ricorrente, identificare integrazione circostante e valutare reload/restart controllato.",
        "automation_level": "manual",
    },
    {
        "category": "Luci e dispositivi",
        "title": "Entita' unavailable anche se dispositivo acceso",
        "patterns": ["unavailable", "device stopped responding", "entity is unavailable"],
        "diagnosis": "Il dispositivo puo' avere segnale debole o connettivita' instabile; le automazioni rischiano di fermarsi.",
        "safe_response": "Solo notifica: suggerisce wait_template/guard condition e miglioramento mesh o rete.",
        "automation_level": "manual",
    },
    {
        "category": "Zigbee",
        "title": "Tutti i dispositivi Zigbee unavailable",
        "patterns": ["all attempts have failed", "timeouterror", "zha", "zigbee"],
        "diagnosis": "Possibile perdita del coordinatore Zigbee, interferenza USB 3.0 o dongle instabile.",
        "safe_response": "Solo notifica; restart HA solo se abilitato esplicitamente.",
        "automation_level": "guarded",
    },
    {
        "category": "Zigbee",
        "title": "Dongle conteso tra ZHA e Zigbee2MQTT",
        "patterns": ["serial", "ezsp", "failed to connect", "adapter", "zigbee2mqtt"],
        "diagnosis": "Il dongle puo' essere conteso o non raggiungibile dal coordinatore scelto.",
        "safe_response": "Solo notifica: verificare ZHA/Z2M e assegnazione del dispositivo.",
        "automation_level": "manual",
    },
    {
        "category": "Zigbee",
        "title": "Entita' MQTT/Z2M non piu' fornita",
        "patterns": ["no longer being provided by the mqtt integration", "mqtt integration"],
        "diagnosis": "Disallineamento tra entita' registrata in HA e nome/ID pubblicato da Zigbee2MQTT.",
        "safe_response": "Solo notifica: rinominare in Z2M o ricreare l'entita' in HA.",
        "automation_level": "manual",
    },
    {
        "category": "Rete e connettivita'",
        "title": "Connect call failed / device stopped responding",
        "patterns": ["connect call failed", "device stopped responding", "connection refused", "host is unreachable"],
        "diagnosis": "Il dispositivo LAN non e' raggiungibile, spesso per IP cambiato o rete instabile.",
        "safe_response": "Solo notifica: suggerisce DHCP reservation o IP statico.",
        "automation_level": "manual",
    },
    {
        "category": "Media e stream",
        "title": "Stream camera terminato",
        "patterns": ["error from stream worker", "stream ended", "no additional packets"],
        "diagnosis": "La camera o il flusso RTSP ha smesso di inviare pacchetti.",
        "safe_response": "Solo notifica: verificare camera/rete/go2rtc; restart automatico richiede mapping add-on o camera.",
        "automation_level": "manual",
    },
    {
        "category": "Media e stream",
        "title": "go2rtc / RTSP timeout",
        "patterns": ["go2rtc", "rtsp://", "i/o timeout", "error=eof"],
        "diagnosis": "go2rtc non riesce a leggere il flusso RTSP dalla camera.",
        "safe_response": "Solo notifica: verificare credenziali, profilo stream, camera e connettivita'.",
        "automation_level": "manual",
    },
    {
        "category": "Media e stream",
        "title": "Chromecast/DLNA non raggiungibile",
        "patterns": ["pychromecast.socket_client", "async_upnp_client", "connect call failed", "connection reset by peer"],
        "diagnosis": "TV o media player non risponde sulla LAN o va in standby.",
        "safe_response": "Solo notifica: usare IP fisso e verificare standby/rete.",
        "automation_level": "manual",
    },
    {
        "category": "Media e stream",
        "title": "Google Cast in failed_unload",
        "patterns": ["failed_unload", "cannot be unloaded", "operationnotallowed", "google cast"],
        "diagnosis": "La config entry Cast e' bloccata in uno stato non scaricabile; i reload automatici falliscono con errore 500.",
        "safe_response": "Solo notifica: serve restart Home Assistant o rimozione/riaggiunta manuale della config entry Cast.",
        "automation_level": "manual",
    },
    {
        "category": "Rete e connettivita'",
        "title": "Broadlink non raggiungibile",
        "patterns": ["broadlink", "network timeout", "no response received within"],
        "diagnosis": "Un Broadlink RM non risponde sulla LAN, spesso per Wi-Fi instabile, IP cambiato o dispositivo spento.",
        "safe_response": "Solo notifica: verificare alimentazione, IP fisso/DHCP reservation e qualita' Wi-Fi.",
        "automation_level": "manual",
    },
    {
        "category": "Integrazioni cloud",
        "title": "EZVIZ API non valida",
        "patterns": ["ezviz", "invalid response from api"],
        "diagnosis": "EZVIZ restituisce risposta non valida, spesso per problema cloud, token o rate limit.",
        "safe_response": "Solo notifica: verificare credenziali e stato servizio; reload richiede entry_id affidabile.",
        "automation_level": "manual",
    },
    {
        "category": "Integrazioni cloud",
        "title": "SmartThings subscription interrotta",
        "patterns": ["pysmartthings", "connection error occurred while subscribing", "transferencodingerror"],
        "diagnosis": "La sottoscrizione eventi SmartThings e' stata interrotta dal lato rete/cloud.",
        "safe_response": "Solo notifica: di solito l'integrazione ritenta; se persiste serve reload/ri-autenticazione.",
        "automation_level": "manual",
    },
    {
        "category": "Backup",
        "title": "Upload backup Synology fallito",
        "patterns": ["upload failed for synology_dsm", "failed to upload backup"],
        "diagnosis": "Home Assistant non e' riuscito a caricare il backup su Synology DSM.",
        "safe_response": "Solo notifica: controllare spazio, permessi, rete e credenziali DSM.",
        "automation_level": "manual",
    },
    {
        "category": "Duck DNS",
        "title": "Duck DNS update fallito",
        "patterns": ["duckdns", "unexpected error fetching duckdns", "update_failed", "connection_error"],
        "diagnosis": "Duck DNS non aggiorna correttamente l'IP o ha un errore interno dell'add-on/integrazione.",
        "safe_response": "Riavvio add-on Duck DNS se consentito; se persiste, verificare token, DNS e connettivita' esterna.",
        "automation_level": "guarded",
    },
    {
        "category": "Add-on",
        "title": "Repository add-on Git non accessibile",
        "patterns": ["failed to to call /store/repositories", "could not read username", "git clone"],
        "diagnosis": "Supervisor sta clonando un repository Git non accessibile senza credenziali.",
        "safe_response": "Solo notifica: rimuovere repo sbagliato/privato e usare URL pubblico corretto.",
        "automation_level": "manual",
    },
    {
        "category": "Supervisor",
        "title": "Config add-on con architetture deprecate",
        "patterns": ["app config 'arch' uses deprecated values", "deprecated values"],
        "diagnosis": "Un add-on dichiara architetture non piu' accettate o deprecate dal Supervisor.",
        "safe_response": "Per questo add-on la correzione e' rimuovere armhf/armv7/i386 dal config.yaml; per add-on di terzi va segnalato al maintainer.",
        "automation_level": "manual",
    },
    {
        "category": "Supervisor",
        "title": "Campo codenotary deprecato",
        "patterns": ["uses deprecated 'codenotary' field", "codenotary"],
        "diagnosis": "Un add-on usa ancora il campo codenotary, ignorato dal Supervisor moderno.",
        "safe_response": "Solo notifica: il campo va rimosso dal maintainer dell'add-on.",
        "automation_level": "manual",
    },
    {
        "category": "Supervisor",
        "title": "Campo advanced deprecato",
        "patterns": ["uses deprecated 'advanced' field"],
        "diagnosis": "Un add-on usa ancora il campo advanced, ormai ignorato dal Supervisor.",
        "safe_response": "Solo notifica: va rimosso dal config dell'add-on dal rispettivo maintainer.",
        "automation_level": "manual",
    },
    {
        "category": "Supervisor",
        "title": "Accesso dispositivi add-on ridondante",
        "patterns": ["has full device access, and selective device access"],
        "diagnosis": "Un add-on dichiara sia accesso completo ai device sia accessi selettivi, configurazione ridondante segnalata dal Supervisor.",
        "safe_response": "Solo notifica: va corretta dal maintainer scegliendo un solo modello di accesso ai device.",
        "automation_level": "manual",
    },
    {
        "category": "Host Docker",
        "title": "Validazione firma immagine Docker fallita",
        "patterns": ["failed to validate image signature", "expected image index descriptor"],
        "diagnosis": "Docker/Supervisor non riesce a validare la firma di una immagine, spesso per manifest non OCI/index.",
        "safe_response": "Solo notifica: verificare repository immagine/add-on e aggiornamento Supervisor; non e' sicuro cancellare immagini automaticamente.",
        "automation_level": "manual",
    },
    {
        "category": "Host Docker",
        "title": "OCI mediatype forzato durante build",
        "patterns": ["forcibly turning on oci-mediatype mode for attestations"],
        "diagnosis": "BuildKit forza il formato OCI per attestazioni durante build add-on.",
        "safe_response": "Informativo: normalmente non richiede intervento se la build finisce con successo.",
        "automation_level": "safe",
    },
    {
        "category": "Host Docker",
        "title": "Docker socket connection reset",
        "patterns": ["error reading preface", "connection reset by peer", "docker.sock"],
        "diagnosis": "Una connessione locale al Docker socket e' stata chiusa durante build/update.",
        "safe_response": "Solo notifica se ricorrente; isolato durante build non richiede intervento.",
        "automation_level": "manual",
    },
    {
        "category": "Supervisor",
        "title": "Proxy WebSocket chiuso dal client",
        "patterns": ["error websocket message received while proxying", "cannot write to closing transport"],
        "diagnosis": "Una connessione WebSocket proxy verso un add-on si e' chiusa mentre Supervisor stava scrivendo.",
        "safe_response": "Solo notifica se isolato; se ricorrente verificare l'add-on indicato e la stabilita' del browser/client.",
        "automation_level": "manual",
    },
    {
        "category": "Rete e connettivita'",
        "title": "CPU al 100% / Home Assistant non raggiungibile",
        "patterns": ["blocked for", "executor", "cpu", "bootstrap", "taking over"],
        "diagnosis": "Una integrazione puo' bloccare il setup o saturare la coda task.",
        "safe_response": "Solo notifica; disabilitare integrazione richiede decisione manuale.",
        "automation_level": "manual",
    },
]


def list_known_issues() -> list[dict]:
    return list(KNOWN_ISSUES)


def match_known_issue(text: str) -> dict | None:
    lowered = text.lower()
    best: dict | None = None
    best_score = 0
    for issue in KNOWN_ISSUES:
        score = sum(1 for pattern in issue["patterns"] if pattern in lowered)
        if score > best_score:
            best = issue
            best_score = score
    return best
